/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Abstratas.Dados;
import Abstratas.Item;
import Classes.Produto;
import Classes.Servico;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class DialogFaturamento extends javax.swing.JDialog {
    private void loadProdutoList(){
        DefaultComboBoxModel cbm = 
        new DefaultComboBoxModel(new Vector(Abstratas.Dados.getListaProduto()));
        comboProduto.setModel(cbm);
    }
    private void loadServicoList(){
        DefaultComboBoxModel cbm = 
        new DefaultComboBoxModel(new Vector(Abstratas.Dados.getListaServico()));
        comboServico.setModel(cbm);
    }
    /**
     * Creates new form DialogFaturamento
     */
    public DialogFaturamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboServico = new javax.swing.JComboBox<>();
        buttonAddProduto = new javax.swing.JButton();
        buttonAddServico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        buttonMostrar = new javax.swing.JButton();
        buttonFaturaInterface = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Produtos");

        comboProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Serviços");

        comboServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonAddProduto.setText("Adicionar");
        buttonAddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddProdutoActionPerformed(evt);
            }
        });

        buttonAddServico.setText("Adicionar");
        buttonAddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddServicoActionPerformed(evt);
            }
        });

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        buttonMostrar.setText("Mostrar Fatura");
        buttonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarActionPerformed(evt);
            }
        });

        buttonFaturaInterface.setText("Mostrar Fatura Interface");
        buttonFaturaInterface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFaturaInterfaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboServico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(buttonAddProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAddServico)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMostrar)
                    .addComponent(buttonFaturaInterface))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddProduto)
                    .addComponent(buttonAddServico))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(buttonMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFaturaInterface)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.loadProdutoList();
        this.loadServicoList();
    }//GEN-LAST:event_formWindowOpened

    private void buttonAddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProdutoActionPerformed
        // TODO add your handling code here:
        if (Abstratas.Dados.getListaProduto().isEmpty()){
            JOptionPane.showMessageDialog(null, "Produtos VAZIO");
            return;
        }
        Produto produto = (Produto)comboProduto.getSelectedItem();
        Abstratas.Dados.getListaFatura().add(produto);
    }//GEN-LAST:event_buttonAddProdutoActionPerformed

    private void buttonAddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddServicoActionPerformed
        // TODO add your handling code here:
        if (Abstratas.Dados.getListaServico().isEmpty()){
            JOptionPane.showMessageDialog(null, "Serviços VAZIO");
            return;
        }
        Servico servico = (Servico)comboServico.getSelectedItem();
        Abstratas.Dados.getListaFatura().add(servico);        
    }//GEN-LAST:event_buttonAddServicoActionPerformed

    private void buttonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarActionPerformed
        // TODO add your handling code here:
        areaTexto.setText("----FATURA---\n");
        double total = 0;
        for (Item object : Abstratas.Dados.getListaFatura()) {
            if (object instanceof Produto){
                Produto produto = (Produto)object;
                areaTexto.append(produto.getNome()+"\t"+produto.getPreco()+"\n");
                total += produto.getPreco();
            }else{
                Servico servico = (Servico)object;
                areaTexto.append(servico.getNome()+"\t"+
                (servico.getNumeroHoras()*Abstratas.Dados.getValorHoraServico())+"\n");
                total+= (servico.getNumeroHoras()*Abstratas.Dados.getValorHoraServico());
            }
        }
        areaTexto.append("Total a Receber: " + total);
    }//GEN-LAST:event_buttonMostrarActionPerformed

    private void buttonFaturaInterfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFaturaInterfaceActionPerformed
        // TODO add your handling code here:
        areaTexto.setText("---Fatura utilizando Interface---\n");
        double soma=0;
        for(Item item : Dados.getListaFatura()){
            areaTexto.append(item.getTipo() + "\t"
                           + item.getNome() + "\t"
                           + item.getValorFatura()+"\n");
            soma += item.getValorFatura();
        }
        areaTexto.append("Total: "+soma);
    }//GEN-LAST:event_buttonFaturaInterfaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFaturamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFaturamento dialog = new DialogFaturamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                      System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton buttonAddProduto;
    private javax.swing.JButton buttonAddServico;
    private javax.swing.JButton buttonFaturaInterface;
    private javax.swing.JButton buttonMostrar;
    private javax.swing.JComboBox<String> comboProduto;
    private javax.swing.JComboBox<String> comboServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
